<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Todays Deals</name>
   <tag></tag>
   <elementGuidId>2584c1da-a753-4998-b887-60a1ff3eb199</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='nav-xshop']/a[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d8e26a0f-ac1a-4a1a-8632-b2c5b89b1dce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/deals?ref_=nav_cs_gb</value>
      <webElementGuid>c423bea9-480c-4541-afac-e29dbea4f4c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-a  </value>
      <webElementGuid>b1cd3dcd-e83a-4b28-85b8-87642b4f8b1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>9630d39e-a18b-43ba-b0ae-d3f9fd29aa25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-type</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>54a80823-e177-4a00-86b4-0a40b667a5f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-slot-id</name>
      <type>Main</type>
      <value>nav_cs_4</value>
      <webElementGuid>6024db12-a804-49cb-b22f-0c46ce83d137</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-content-id</name>
      <type>Main</type>
      <value>nav_cs_gb</value>
      <webElementGuid>cd4ce787-605d-4aef-b926-4b5f70983f9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-id</name>
      <type>Main</type>
      <value>ko6kw3-91oeev-60yby8-24wuca</value>
      <webElementGuid>f05a426a-d3c3-4f88-8f72-0598946fef6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Today's Deals</value>
      <webElementGuid>2a6b5513-f4c7-4f1a-b557-a8ace737d536</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-xshop&quot;)/a[@class=&quot;nav-a&quot;]</value>
      <webElementGuid>c5fae299-972c-42f6-a8c7-ed9bc76070d5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-xshop']/a[5]</value>
      <webElementGuid>f888e876-7a34-4ddf-b5e9-9f1779d27021</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mobiles'])[1]/following::a[1]</value>
      <webElementGuid>e3d1ba4c-fcd3-418a-ae93-ad2913d5483e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Best Sellers'])[1]/following::a[2]</value>
      <webElementGuid>92227902-364a-4a43-8d9e-658957ca384e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer Service'])[1]/preceding::a[1]</value>
      <webElementGuid>b1897ab3-80c0-4530-8aa5-a36efcc36605</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Electronics'])[2]/preceding::a[2]</value>
      <webElementGuid>a1201c39-7100-4004-87e0-673841b87cc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/deals?ref_=nav_cs_gb')]</value>
      <webElementGuid>cf528174-a16b-4c57-8947-70923aefecc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/div/a[5]</value>
      <webElementGuid>7d4a1203-dc27-403c-ba82-e5aae8095431</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/deals?ref_=nav_cs_gb' and (text() = concat(&quot;Today&quot; , &quot;'&quot; , &quot;s Deals&quot;) or . = concat(&quot;Today&quot; , &quot;'&quot; , &quot;s Deals&quot;))]</value>
      <webElementGuid>7c1a9f61-fa61-4a15-97c7-9a1401a36614</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
