<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_and up</name>
   <tag></tag>
   <elementGuidId>121f9bc2-6b99-468f-87a3-54afd22c1e46</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='grid-main-container']/div[2]/span[4]/ul/li/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span:nth-of-type(4) > ul.a-nostyle > li.LinkFilterOption-module__linkFilterOptionListElement_AzC4LFMfeFF1CkwveJM01 > div.a-row > a.LinkFilterOption-module__linkFilterOption_k3Xp4bgxEaBmcgTA0UAxc</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>756391d4-d1b7-4e50-8087-45ad30b5ae02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6c117ecf-0146-4855-abfa-8af1087c0dd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-pressed</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>60d7b1a5-78a0-443b-a194-34dbfab41b84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>LinkFilterOption-module__linkFilterOption_k3Xp4bgxEaBmcgTA0UAxc</value>
      <webElementGuid>fefe5cd9-cde1-49ed-992d-c68ac401f449</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>7cf1a86b-1b79-4796-9ccc-754449e86fa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-type</name>
      <type>Main</type>
      <value>uxElement</value>
      <webElementGuid>ec55f724-d63c-40fc-980f-ccd99f3f884e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-element-id</name>
      <type>Main</type>
      <value>filter-star-rating-4</value>
      <webElementGuid>6df09f70-3093-43d4-8cdc-f0a600bc156d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-element-type</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>53b5a510-bec4-4314-a78e-cdce116817e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-id</name>
      <type>Main</type>
      <value>ntkgfu-nar2z7-mbuo4u-8snh2w</value>
      <webElementGuid>8f356247-95e1-433a-bdaf-3b47d28f5dd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>and up</value>
      <webElementGuid>5f4d24da-e9f8-43a2-a2e8-d287ccf0194e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;grid-main-container&quot;)/div[@class=&quot;GridFilters-module__gridFilterSection_36xNFAVppWfx4i4otzVc2Y&quot;]/span[4]/ul[@class=&quot;a-nostyle&quot;]/li[@class=&quot;LinkFilterOption-module__linkFilterOptionListElement_AzC4LFMfeFF1CkwveJM01&quot;]/div[@class=&quot;a-row&quot;]/a[@class=&quot;LinkFilterOption-module__linkFilterOption_k3Xp4bgxEaBmcgTA0UAxc&quot;]</value>
      <webElementGuid>e536e1b0-910a-44bc-9afc-1d30cc660d29</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='grid-main-container']/div[2]/span[4]/ul/li/div/a</value>
      <webElementGuid>1b613e3d-04b1-4a20-ba5e-d9ba40b0a927</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Average Customer Review'])[1]/following::a[1]</value>
      <webElementGuid>d56cde57-5655-4790-8713-c9f0a94bdcee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All deals'])[2]/following::a[5]</value>
      <webElementGuid>477f2a55-e14f-4349-a1ab-f29ab99a71c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='and up'])[2]/preceding::a[1]</value>
      <webElementGuid>e8b3c8b3-365c-46cf-9a9f-cccc942e158f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[15]</value>
      <webElementGuid>cf609442-70ed-4f26-a9d9-14a5da84b1ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[4]/ul/li/div/a</value>
      <webElementGuid>a173d389-d7d8-4d46-993b-5a4a76d986c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'and up' or . = 'and up')]</value>
      <webElementGuid>c379590c-41a0-4e45-a101-b44d0701deb7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
